version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
      #docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run: |
         echo "$CODEBERG_ACCESS_KEY" | docker login -u seungjin --password-stdin codeberg.org
      - run: |
          docker build --platform linux/amd64 -t codeberg.org/sa/mstd-random-cafe:ci-$pipeline.number .
      - run: |
          docker push codeberg.org/sa/mstd-random-cafe:ci-$pipeline.number





































--**-Mg: config.yml                       (fundamental-c)--L7--C33-------------------------------------------------
