version: 2.1
jobs:
  build:
    working_directory: /app
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker buildx build --platform linux/amd64,linux/aarch64 -t codeberg.org/sa/mstd-random-restaurant:lates$





































--**-Mg: config.yml                       (fundamental-c)--L7--C33-------------------------------------------------
